name: pysces
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.22
  - scipy>=1.8
  - pandas>=1.4
  - scikit-learn>=1.0
  - anndata>=0.8
  - scanpy>=1.9
  - matplotlib>=3.5
  - seaborn>=0.12
  - pybind11>=2.10.0
  - cmake>=3.24
  - pytest>=7.0
  - sphinx>=5.0
  - jupyterlab
  - pip
  # Optional dependencies for Census integration and acceleration
  - pip:
    - cellxgene-census[experimental]>=0.2.1
    - tiledb-soma
    - numba>=0.56  # For performance optimization
